# Generated by Django 5.2.10 on 2026-01-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_add_quiz_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='mark',
            field=models.PositiveIntegerField(default=0, help_text='Percentage mark (0–100)'),
        ),
    ]
